In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("cars.csv")
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [3]:
df["normalized-losses"].replace("?",np.nan,inplace=True)
df["horsepower"].replace("?",np.nan,inplace=True)

In [4]:
df["normalized-losses"]=df["normalized-losses"].astype("float")
df["horsepower"]=df["horsepower"].astype("float")

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
si = SimpleImputer(strategy="mean")

In [7]:
df[["normalized-losses","horsepower"]]=si.fit_transform(df[["normalized-losses","horsepower"]])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   body-style         205 non-null    object
 5   drive-wheels       205 non-null    object
 6   engine-location    205 non-null    object
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    float64
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(4), int64(5), object(6)
memory usage: 24.1+ KB

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder()

In [11]:
oe.fit_transform(df[["make","body-style"]])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  2.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  3.],
       [ 1.,  4.],
       [ 1.,  3.],
       [ 1.,  2.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.],
       [ 3.,  2.],
       [ 3.,  2.],
       [ 3.,  3.],
       [ 4.,  2.],
       [ 4.,  2.],
       [ 4.,  2.],
       [ 4.,  2.],
       [ 4.,  3.],
       [ 4.,  3.],
       [ 4.,  3.],
       [ 4.,  4.],
       [ 4.,  2.],
       [ 5.,  2.],
       [ 5.,  2.],
       [ 5.,  2.],
       [ 5.,  2.],
       [ 5.,  2.],
       [ 5.,  3.],
       [ 5.,  4.],
       [ 5.,  2.],
       [ 5.,  2.],
       [ 5.,  3.],
       [ 5.,  3.],
       [ 5.,  3.],
       [ 5.,  3.],
       [ 6.,  3.],
       [ 6.,  3.],
       [ 6.,  3.],
       [ 6.,  2.],
       [ 7.,  3.],
       [ 7.,  3.],
       [ 7.,  3.],
       [ 8.,  2.],
       [ 8.,  2.],
       [ 8.,  2.],
       [ 8.,  3.],
       [ 8.,  3.],
       [ 8.,  2.],
       [ 8.,  2.],
       [ 8.,  2.],
       [ 8.,  2.],
       [ 8.,  2.],
       [ 8.,  3.],
       [ 8.,  2.],
       [ 8.,  3.],
       [ 8.,  3.],
       [ 8.,  2.],
       [ 8.,  3.],
       [ 8.,  3.],
       [ 9.,  3.],
       [ 9.,  4.],
       [ 9.,  1.],
       [ 9.,  3.],
       [ 9.,  3.],
       [ 9.,  0.],
       [ 9.,  3.],
       [ 9.,  1.],
       [10.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  2.],
       [11.,  3.],
       [11.,  3.],
       [11.,  3.],
       [11.,  3.],
       [12.,  3.],
       [12.,  3.],
       [12.,  3.],
       [12.,  3.],
       [12.,  4.],
       [12.,  3.],
       [12.,  2.],
       [12.,  3.],
       [12.,  4.],
       [12.,  1.],
       [12.,  2.],
       [12.,  3.],
       [12.,  3.],
       [12.,  4.],
       [12.,  3.],
       [12.,  2.],
       [12.,  2.],
       [12.,  2.],
       [13.,  3.],
       [13.,  3.],
       [13.,  4.],
       [13.,  4.],
       [13.,  3.],
       [13.,  3.],
       [13.,  4.],
       [13.,  4.],
       [13.,  3.],
       [13.,  3.],
       [13.,  3.],
       [14.,  2.],
       [14.,  2.],
       [14.,  2.],
       [14.,  3.],
       [14.,  3.],
       [14.,  4.],
       [14.,  2.],
       [15.,  2.],
       [15.,  1.],
       [15.,  1.],
       [15.,  0.],
       [15.,  2.],
       [16.,  4.],
       [16.,  2.],
       [17.,  2.],
       [17.,  3.],
       [17.,  2.],
       [17.,  3.],
       [17.,  2.],
       [17.,  3.],
       [18.,  2.],
       [18.,  2.],
       [18.,  2.],
       [18.,  3.],
       [18.,  3.],
       [18.,  3.],
       [18.,  3.],
       [18.,  3.],
       [18.,  4.],
       [18.,  4.],
       [18.,  4.],
       [18.,  4.],
       [19.,  2.],
       [19.,  2.],
       [19.,  2.],
       [19.,  4.],
       [19.,  4.],
       [19.,  4.],
       [19.,  3.],
       [19.,  2.],
       [19.,  3.],
       [19.,  2.],
       [19.,  3.],
       [19.,  2.],
       [19.,  3.],
       [19.,  3.],
       [19.,  2.],
       [19.,  3.],
       [19.,  2.],
       [19.,  1.],
       [19.,  1.],
       [19.,  2.],
       [19.,  1.],
       [19.,  2.],
       [19.,  0.],
       [19.,  3.],
       [19.,  3.],
       [19.,  2.],
       [19.,  3.],
       [19.,  2.],
       [19.,  2.],
       [19.,  2.],
       [19.,  3.],
       [19.,  4.],
       [20.,  3.],
       [20.,  3.],
       [20.,  3.],
       [20.,  3.],
       [20.,  3.],
       [20.,  3.],
       [20.,  3.],
       [20.,  0.],
       [20.,  2.],
       [20.,  3.],
       [20.,  3.],
       [20.,  4.],
       [21.,  3.],
       [21.,  4.],
       [21.,  3.],
       [21.,  4.],
       [21.,  3.],
       [21.,  4.],
       [21.,  3.],
       [21.,  3.],
       [21.,  3.],
       [21.,  3.],
       [21.,  3.]])

In [12]:
catcol = df.select_dtypes(object).columns

In [13]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

df[catcol]=oe.fit_transform(df[catcol])

In [14]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,13495
1,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,16500
2,1,122.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26,16500
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30,13950
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,23,28,16845
201,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.8,55.5,3.0,141,160.0,19,25,19045
202,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,5.0,173,134.0,18,23,21485
203,-1,95.0,21.0,0.0,3.0,2.0,0.0,68.9,55.5,3.0,145,106.0,26,27,22470
204,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,19,25,22625

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    float64
 3   fuel-type          205 non-null    float64
 4   body-style         205 non-null    float64
 5   drive-wheels       205 non-null    float64
 6   engine-location    205 non-null    float64
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    float64
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    float64
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(10), int64(5)
memory usage: 24.1 KB

In [16]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [17]:
x

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg
0,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27
1,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27
2,1,122.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,23,28
201,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.8,55.5,3.0,141,160.0,19,25
202,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,5.0,173,134.0,18,23
203,-1,95.0,21.0,0.0,3.0,2.0,0.0,68.9,55.5,3.0,145,106.0,26,27
204,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,19,25

In [18]:
y

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: int64

In [19]:
x.shape

(205, 14)

In [20]:
y.shape

(205,)

In [21]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)

In [22]:
xtrain

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg
124,3,122.0,14.0,1.0,2.0,2.0,0.0,66.3,50.2,3.0,156,145.0,19,24
181,-1,122.0,19.0,1.0,4.0,2.0,0.0,66.5,54.1,0.0,161,156.0,19,24
154,0,81.0,19.0,1.0,4.0,0.0,0.0,63.6,59.1,3.0,92,62.0,27,32
53,1,113.0,8.0,1.0,3.0,1.0,0.0,64.2,54.1,3.0,91,68.0,31,38
94,1,128.0,12.0,1.0,3.0,1.0,0.0,63.8,54.5,3.0,97,69.0,31,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,2,104.0,17.0,1.0,3.0,1.0,0.0,66.5,56.1,3.0,121,110.0,21,28
137,2,104.0,17.0,1.0,3.0,1.0,0.0,66.5,56.1,0.0,121,160.0,19,26
72,3,142.0,9.0,1.0,0.0,2.0,0.0,70.5,50.8,5.0,234,155.0,16,18
140,2,83.0,18.0,1.0,2.0,0.0,0.0,63.8,55.7,4.0,108,73.0,26,31
37,0,106.0,5.0,1.0,2.0,1.0,0.0,65.2,53.3,3.0,110,86.0,27,33

In [23]:
ytrain

124    12764
181    15750
154     7898
53      6695
94      7299
       ...
133    12170
137    18620
72     35056
140     7603
37      7895
Name: price, Length: 143, dtype: int64

In [24]:
xtest

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg
78,2,161.0,11.0,1.0,2.0,1.0,0.0,64.4,50.8,3.0,92,68.0,31,38
97,1,103.0,12.0,1.0,4.0,1.0,0.0,63.8,53.5,3.0,97,69.0,31,37
151,1,87.0,19.0,1.0,2.0,1.0,0.0,63.6,54.5,3.0,92,62.0,31,38
44,1,122.0,6.0,1.0,3.0,1.0,0.0,63.6,52.0,3.0,90,70.0,38,43
40,0,85.0,5.0,1.0,3.0,1.0,0.0,62.5,54.1,3.0,110,86.0,27,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,0,85.0,5.0,1.0,3.0,1.0,0.0,65.2,54.1,3.0,110,86.0,27,33
110,0,122.0,13.0,0.0,4.0,2.0,0.0,68.4,58.7,2.0,152,95.0,25,25
164,1,168.0,19.0,1.0,2.0,2.0,0.0,64.0,52.6,3.0,98,70.0,29,34
56,3,150.0,8.0,1.0,2.0,2.0,0.0,65.7,49.6,6.0,70,101.0,17,23
176,-1,65.0,19.0,1.0,3.0,1.0,0.0,66.5,54.9,3.0,122,92.0,27,32

# Linear Regression

In [26]:
from sklearn.linear_model import LinearRegression

linreg = LinearRegression()

linreg.fit(xtrain,ytrain)

ypred = linreg.predict(xtest)

In [27]:
from sklearn.metrics import r2_score

print(r2_score(ytest,ypred))

0.796556678039738

In [28]:
train = linreg.score(xtrain,ytrain)

test = linreg.score(xtest,ytest)

print(f"Training Result :- {train}")
print(f"Testing Result :- {test}")

Training Result :- 0.8504573774895475
Testing Result :- 0.796556678039738

In [29]:
#High Accuarcy ---> Low Training Error --> Low Bias

#Low Accuracy --->High Testing Error --->High Variance

#Low Bias + High Variance = Overfitting

In [30]:
linreg.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

In [43]:
from sklearn.linear_model import Ridge,Lasso

l2 = Ridge(alpha=8)
l2.fit(xtrain,ytrain)
ypred = l2.predict(xtest)

In [44]:
train = l2.score(xtrain,ytrain)

test = l2.score(xtest,ytest)

print(f"Training Result :- {train}")
print(f"Testing Result :- {test}")

Training Result :- 0.8141763553347592
Testing Result :- 0.8149010602831951

# Hyperparameter Tuning

In [38]:
for i in range(1,50):
    l2 = Ridge(alpha=i)
    l2.fit(xtrain,ytrain)
    
    train = l2.score(xtrain,ytrain)
    test = l2.score(xtest,ytest)
    
    print(f"{i} {train} {test}")

1 0.8436019887231635 0.8074518758147272
2 0.8356568294333326 0.8110292248150514
3 0.8295966853783839 0.8126933383890032
4 0.8250050456621347 0.8136148645029295
5 0.8214255248858177 0.8141745853539418
6 0.8185497905642731 0.8145301242133354
7 0.8161775446879697 0.8147582608502812
8 0.8141763553347592 0.8149010602831951
9 0.8124561449821562 0.8149836949253051
10 0.8109538582620313 0.8150222867376528
11 0.8096241695970484 0.8150277245431788
12 0.8084337140523128 0.8150076788279416
13 0.8073574061115951 0.8149677381788257
14 0.8063760269401785 0.8149120868051176
15 0.8054746030665225 0.8148439278252516
16 0.804641291734184 0.8147657584947389
17 0.8038665985400393 0.8146795554128125
18 0.8031428178838971 0.8145869029046833
19 0.8024636258876572 0.8144890843369585
20 0.8018237796035675 0.8143871485445551
21 0.8012188915864451 0.8142819591129822
22 0.8006452587395114 0.8141742315788492
23 0.8000997308073305 0.8140645619421539
24 0.7995796082141254 0.8139534488166058
25 0.7990825618875557 0.8138413108452036
26 0.7986065697399167 0.813728500540377
27 0.7981498659021868 0.813615315388484
28 0.797710899816778 0.8135020068362638
29 0.7972883030209656 0.813388787619721
30 0.7968808619807591 0.8132758377831448
31 0.7964874957227427 0.813163309653795
32 0.7961072372991725 0.8130513319772293
33 0.7957392183371694 0.8129400133729975
34 0.7953826560857553 0.812829445236302
35 0.7950368424986247 0.8127197041851852
36 0.7947011349858958 0.81261085413278
37 0.7943749485418696 0.8125029480485759
38 0.7940577490133227 0.8123960294605082
39 0.7937490473179628 0.8122901337400303
40 0.7934483944582853 0.8121852892047274
41 0.7931553772043528 0.812081518066906
42 0.7928696143416054 0.8119788372516916
43 0.7925907533979553 0.8118772591041922
44 0.7923184677790721 0.8117767920020493
45 0.7920524542526479 0.8116774408870528
46 0.7917924307321205 0.8115792077273268
47 0.7915381343182769 0.8114820919198036
48 0.7912893195636811 0.8113860906412014
49 0.7910457569302702 0.8112911991545093